language: android
android:
  components:
    - build-tools-29.0.2
    - android-29

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew install

deploy:
  provider: script
  script: ./gradlew :ble-android-library:assembleRelease :ble-android-library:bintrayUpload
  skip_cleanup: true
  file: bintray
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    branch: master