name: Release 

on: 
  push:
    branches:
      - 'master'

jobs:         
  publish:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: pre-build
        run: chmod +x gradlew
      - name: install
        run: ./gradlew install
      - name: assemble
        run: ./gradlew :ble-android-library:assembleRelease
      - name: bintray upload
        env: 
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew :ble-android-library:bintrayUpload
